### ISSUE TITLE
Syntax Error creating RPM Package

### ISSUE THREAD

**Issue by TomBous** [RPM-Outpost/typora#1]
**OS** : Fedora 26
**Desktop** : Gnome 3.24
Hi ! 
First of all thank you for your work, it's really appreciated. I just  updated to Fedora 26 and i get this problem, any help ? There is no RPM file output.

![capture d ecran de 2017-09-25 19-58-35](https://user-images.githubusercontent.com/10131977/30823531-c164ba08-a22c-11e7-9790-e3d29339921f.png)

**Comment by TheElectronWill** [comment]
Hello !
The fedora tools that build the RPM package do not support paths with accents like `Téléchargements`. It's a known limitation of the RPM devtools that I apparently can't fix :-/
Move the repository to another folder, like the Documents, and it should work.

**Comment by TomBous** [comment]
That was it ! 
Thanks for the help and for your reactivity :-) 
Problem is solved, i close the issue. 
Keep up the good work ! Cheers

**Comment by TheElectronWill** [comment]
You're welcome :-)
