### ISSUE TITLE
Can't create package the RPM package for x86_64

### ISSUE THREAD

**Issue by BruceChen2017** [RPM-Outpost/typora#2]
I am also on Fedora 26
when finishing downloading:
```
Extracting "Typora-linux.tar.gz"...
Analysing the files...
 -> Infos path: resources/app/package.json
 -> Icons path: resources/app/asserts/icon
 -> Version: 0.9.37
Creating the .desktop file...
Creating the RPM package for x86_64 (this may take a while)...
  File "<stdin>", line 3
SyntaxError: Non-ASCII character '\xe4' in file <stdin> on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
error：/var/tmp/rpm-tmp.fT7N5m (%install) bad exit status
    /var/tmp/rpm-tmp.fT7N5m (%install) bad exit status
```

**Comment by TheElectronWill** [comment]
Does your path contain some accents or special characters ? This is not supported by the rpm tools (not because of my script). Please see this other issue: https://github.com/RPM-Outpost/typora/issues/1

**Comment by BruceChen2017** [comment]
@TheElectronWill It works,thanks!Maybe you should add some check in the script or FAQ for this problem in case of repeating same issue by others in the future

**Comment by TheElectronWill** [comment]
You're welcome ! 
I'll add a warning to the readme and I'll try to find a way to add a check in the script.
