### ISSUE TITLE
CentOS dependencies

### ISSUE THREAD

**Issue by triangulum** [RPM-Outpost/typora#4]
On CentOS, the script successfully downloads the .tar.gz and builds an RPM. But there seems to be an issue with dependencies, which means the installation is not completed successfully.

Is this a known issue?

```bash
--> Finished Dependency Resolution
Error: Package: typora-0.9.65-0.el7.x86_64 (/typora-0.9.65-0.el7.x86_64)
           Requires: libstdc++.so.6(GLIBCXX_3.4.21)(64bit)
Error: Package: typora-0.9.65-0.el7.x86_64 (/typora-0.9.65-0.el7.x86_64)
           Requires: libstdc++.so.6(GLIBCXX_3.4.20)(64bit)
Error: Package: typora-0.9.65-0.el7.x86_64 (/typora-0.9.65-0.el7.x86_64)
           Requires: libstdc++.so.6(CXXABI_1.3.9)(64bit)
```

**Comment by Turiok** [comment]
Yes, it's a known issues. Centos is Centos. An OS which use old version components. And Typora use a gcc version compiler that's newer than on Centos.

Sorry for my english. It's not my language.
