### ISSUE TITLE
error: Macro %pkg_version has empty body  ---- Fedora 31

### ISSUE THREAD

**Issue by GlacierFox** [RPM-Outpost/typora#7]
I'm getting an error when it comes to compiling the RPM. I'm left with nothing to install in the RPM folder. I've successfully installed Typora using this script a few months ago, just looking to build an updated RPM using your script again.

> Downloading Typora for linux...
> /home/danny/Downloa 100%[===================>]  75.76M  5.02MB/s    in 18s     
> 
> Extracting "Typora-linux.tar.gz"...
> Analysing the files...
> cat: /home/danny/Downloads/typora-master/work/typora/resources/app/package.json: No such file or directory
>  -> Infos path: resources/app/package.json
>  -> Icons path: resources/app/asserts/icon
>  -> Version: 
> Creating the .desktop file...
> Creating the RPM package for x86_64 (this may take a while)...
> error: Macro %pkg_version has empty body
> Done!
> The RPM package is located in the "RPMs/x86_64" folder.
> 

Nothing gets built into the RPM folder.

**Comment by CodedOre** [comment]
The Developer of Typora has changed the Archive, so we need now to ignore two Folders. If you want to solve it, change `--strip 1` to `--strip 2` in Line 73 of `create-package.sh`. This should solve your problem.

**Comment by GlacierFox** [comment]
> The Developer of Typora has changed the Archive, so we need now to ignore two Folders. If you want to solve it, change `--strip 1` to `--strip 2` in Line 73 of `create-package.sh`. This should solve your problem.

This worked brilliantly thank you!
